// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: framework/envelope.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnvelopeFlag 使用枚举来描述各类标志位的含义。
// 实际存储时，flags 字段为一个 64 位整数，通过按位或进行组合。
type EnvelopeFlag int32

const (
	EnvelopeFlag_ENVELOPE_FLAG_UNSPECIFIED EnvelopeFlag = 0
	// ENVELOPE_FLAG_COMPRESSED 表示 payload 已经过压缩（例如 zstd）。
	EnvelopeFlag_ENVELOPE_FLAG_COMPRESSED EnvelopeFlag = 1
	// ENVELOPE_FLAG_ENCRYPTED 表示 payload 已经过加密（例如 AES‑GCM）。
	EnvelopeFlag_ENVELOPE_FLAG_ENCRYPTED EnvelopeFlag = 2
)

// Enum value maps for EnvelopeFlag.
var (
	EnvelopeFlag_name = map[int32]string{
		0: "ENVELOPE_FLAG_UNSPECIFIED",
		1: "ENVELOPE_FLAG_COMPRESSED",
		2: "ENVELOPE_FLAG_ENCRYPTED",
	}
	EnvelopeFlag_value = map[string]int32{
		"ENVELOPE_FLAG_UNSPECIFIED": 0,
		"ENVELOPE_FLAG_COMPRESSED":  1,
		"ENVELOPE_FLAG_ENCRYPTED":   2,
	}
)

func (x EnvelopeFlag) Enum() *EnvelopeFlag {
	p := new(EnvelopeFlag)
	*p = x
	return p
}

func (x EnvelopeFlag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvelopeFlag) Descriptor() protoreflect.EnumDescriptor {
	return file_framework_envelope_proto_enumTypes[0].Descriptor()
}

func (EnvelopeFlag) Type() protoreflect.EnumType {
	return &file_framework_envelope_proto_enumTypes[0]
}

func (x EnvelopeFlag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvelopeFlag.Descriptor instead.
func (EnvelopeFlag) EnumDescriptor() ([]byte, []int) {
	return file_framework_envelope_proto_rawDescGZIP(), []int{0}
}

// Envelope 表示一条在网络中传输的协议消息包。
//
// 说明：
//   - op        ：协议 ID，用于路由到具体业务逻辑。
//   - seq       ：协议序号，用于请求/响应匹配、重放保护等。
//   - payload   ：业务层序列化后的消息体（JSON / Protobuf 等）。
//   - size      ：payload 的字节长度，便于快速校验或预分配缓冲区。
//   - flags     ：使用 EnvelopeFlag 的位标志，描述是否压缩、是否加密等。
//   - sign      ：签名 / MAC，用于防篡改与身份校验（由上层约定算法）。
//   - timestamp ：发送时间戳（Unix 时间，单位由上层约定：秒/毫秒/纳秒）。
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            uint32                 `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Size          uint32                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Flags         uint64                 `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"`
	Sign          []byte                 `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_framework_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_framework_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_framework_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetOp() uint32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *Envelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Envelope) GetFlags() uint64 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Envelope) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

func (x *Envelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_framework_envelope_proto protoreflect.FileDescriptor

const file_framework_envelope_proto_rawDesc = "" +
	"\n" +
	"\x18framework/envelope.proto\x12\x17zeus.framework.internal\"\xa2\x01\n" +
	"\bEnvelope\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\rR\x02op\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\x12\x14\n" +
	"\x05flags\x18\x05 \x01(\x04R\x05flags\x12\x12\n" +
	"\x04sign\x18\x06 \x01(\fR\x04sign\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp*h\n" +
	"\fEnvelopeFlag\x12\x1d\n" +
	"\x19ENVELOPE_FLAG_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ENVELOPE_FLAG_COMPRESSED\x10\x01\x12\x1b\n" +
	"\x17ENVELOPE_FLAG_ENCRYPTED\x10\x02BAZ?github.com/lk2023060901/danmu-garden-framework-protos/frameworkb\x06proto3"

var (
	file_framework_envelope_proto_rawDescOnce sync.Once
	file_framework_envelope_proto_rawDescData []byte
)

func file_framework_envelope_proto_rawDescGZIP() []byte {
	file_framework_envelope_proto_rawDescOnce.Do(func() {
		file_framework_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_framework_envelope_proto_rawDesc), len(file_framework_envelope_proto_rawDesc)))
	})
	return file_framework_envelope_proto_rawDescData
}

var file_framework_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_framework_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_framework_envelope_proto_goTypes = []any{
	(EnvelopeFlag)(0), // 0: zeus.framework.internal.EnvelopeFlag
	(*Envelope)(nil),  // 1: zeus.framework.internal.Envelope
}
var file_framework_envelope_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_framework_envelope_proto_init() }
func file_framework_envelope_proto_init() {
	if File_framework_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_framework_envelope_proto_rawDesc), len(file_framework_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_framework_envelope_proto_goTypes,
		DependencyIndexes: file_framework_envelope_proto_depIdxs,
		EnumInfos:         file_framework_envelope_proto_enumTypes,
		MessageInfos:      file_framework_envelope_proto_msgTypes,
	}.Build()
	File_framework_envelope_proto = out.File
	file_framework_envelope_proto_goTypes = nil
	file_framework_envelope_proto_depIdxs = nil
}
